vim9script

# Download plug.vim if it doesn't exist yet
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
                \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

# Run PlugInstall if there are missing plugins
autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)')) > 0
            \| PlugInstall --sync | source $MYVIMRC
            \| endif

plug#begin("~/.local/share/vim-plug/")
Plug '~/git/vimcomplete'
plug#end()

set laststatus=2
set hidden

# set background=dark
# colorscheme quiet
# hi Normal ctermfg=255 ctermbg=16
# hi Comment cterm=bold ctermfg=243
